var name = 'VAR';
var letter='NODE JS '+name+' NODE JS NODE JS NODE '+ name+ ' JS NODE JS NODE '+name+' JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS NODE JS ';
console.log(letter);